Repository SkillsFundingAgency/das-forecasting-tool, pull requests merged in 2018-06, with the labels that each got.

#86 CI-863 - Change to negative currency format
  src/SFA.DAS.Forecasting.Web/Extensions/DecimalExtensions.cs
Labels: Ready to Release

#70 CI-819 code complete with tests
  src/SFA.DAS.Forecasting.Application.UnitTests/Estimations/Validation/AddApprenticeshipValidatorTests.cs
  src/SFA.DAS.Forecasting.Application/Estimations/Validation/AddApprenticeshipValidation/ValidStartMonth.cs
  src/SFA.DAS.Forecasting.Domain/Shared/Validation/AddApprenticeshipValidationDetail.cs
  src/SFA.DAS.Forecasting.Web/Views/Estimation/AddApprenticeships.cshtml
Labels: Ready to Release

#92 CI-875 -> PreLoad all employers
  src/SFA.DAS.Forecasting.AcceptanceTests/App.config
  src/SFA.DAS.Forecasting.AcceptanceTests/Infrastructure/Config.cs
  src/SFA.DAS.Forecasting.AcceptanceTests/Payments/Feature/PreLoadPayments.feature
  src/SFA.DAS.Forecasting.AcceptanceTests/Payments/Feature/PreLoadPayments.feature.cs
  src/SFA.DAS.Forecasting.AcceptanceTests/Payments/Steps/Pre_LoadPaymentsSteps.cs
  src/SFA.DAS.Forecasting.AcceptanceTests/SFA.DAS.Forecasting.AcceptanceTests.csproj
  src/SFA.DAS.Forecasting.Application/Infrastructure/Registries/ConfigurationHelper.cs
  src/SFA.DAS.Forecasting.Application/Infrastructure/Registries/DefaultRegistry.cs
  src/SFA.DAS.Forecasting.Application/Payments/Messages/PreLoad/AllEmployersPreLoadPaymentRequest.cs
  src/SFA.DAS.Forecasting.Application/Payments/Services/DevPaymentsEventsApiClient.cs
  src/SFA.DAS.Forecasting.Application/SFA.DAS.Forecasting.Application.csproj
  src/SFA.DAS.Forecasting.Application/Shared/Services/EmployerDatabaseService.cs
  src/SFA.DAS.Forecasting.Functions.Framework/Logging/LoggerSetup.cs
  src/SFA.DAS.Forecasting.PreLoad.Functions/AllEmployersPaymentPreLoadHttpFunction.cs
  src/SFA.DAS.Forecasting.PreLoad.Functions/GetEarningDetailsFunction.cs
Labels: Ready for Test

#99 CI-887 -> Change heading from Future funds to Balance in CSV
  src/SFA.DAS.Forecasting.Web.AcceptanceTests/StepDefinition/DownloadForecastBalanceSheetSteps.cs
  src/SFA.DAS.Forecasting.Web/ViewModels/BalanceCsvItemViewModel.cs
Labels: Ready for Test

#97 CI-854 roll over text
  src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie6.css
  src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie7.css
  src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie8.css
  src/SFA.DAS.Forecasting.Web/Content/dist/css/screen.css
  src/SFA.DAS.Forecasting.Web/Content/src/sass/_custom.scss
  src/SFA.DAS.Forecasting.Web/Views/Forecasting/Balance.cshtml
Labels: do not merge

#89 CI-479 -> projections - reordered columns, added expired col, content …
  src/SFA.DAS.Forecasting.Web/Orchestrators/ForcastingOrchestrator.cs
  src/SFA.DAS.Forecasting.Web/ViewModels/BalanceViewModel.cs
  src/SFA.DAS.Forecasting.Web/Views/Forecasting/Balance.cshtml
Labels: do not merge

#100 CI-891 -> Updated text
  src/SFA.DAS.Forecasting.Web/Views/Forecasting/Balance.cshtml
Labels: Ready for Test

#102 CI-890 -> Add survey to projection
  src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie6.css
  src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie7.css
  src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie8.css
  src/SFA.DAS.Forecasting.Web/Content/dist/css/screen.css
  src/SFA.DAS.Forecasting.Web/Content/src/sass/_custom.scss
  src/SFA.DAS.Forecasting.Web/Views/Forecasting/Balance.cshtml
Labels: Ready for Test
