Repository SkillsFundingAgency/das-forecasting-tool, pull requests merged in 2018-07, with the labels that each got.

#109 CI-911, CI-910
  src/SFA.DAS.Forecasting.Web/Content/dist/js/add-apprenticeship-custom.js
  src/SFA.DAS.Forecasting.Web/Content/dist/js/apprenticeships.js
  src/SFA.DAS.Forecasting.Web/Controllers/EstimationController.cs
  src/SFA.DAS.Forecasting.Web/Extensions/StringExtension.cs
  src/SFA.DAS.Forecasting.Web/Orchestrators/Estimations/EstimationOrchestrator.cs
  src/SFA.DAS.Forecasting.Web/SFA.DAS.Forecasting.Web.csproj
  src/SFA.DAS.Forecasting.Web/ViewModels/EditApprenticeshipsViewModel.cs
  src/SFA.DAS.Forecasting.Web/ViewModels/Validation/EditApprenticeshipsViewModelValidator.cs
  src/SFA.DAS.Forecasting.Web/Views/Estimation/AddApprenticeships.cshtml
  src/SFA.DAS.Forecasting.Web/Views/Estimation/EditApprenticeships.cshtml
Labels: Ready to Release

#93 CI-684 levy projection versus modelled cost tab
  src/SFA.DAS.Forecasting.Domain.UnitTests/Estimations/AccountEstimationProjectionTests.cs
  src/SFA.DAS.Forecasting.Domain/Estimations/AccountEstimationProjection.cs
  src/SFA.DAS.Forecasting.Web/Content/dist/js/screen.js
  src/SFA.DAS.Forecasting.Web/Orchestrators/Estimations/EstimationOrchestrator.cs
  src/SFA.DAS.Forecasting.Web/ViewModels/AccountFundsViewModel.cs
  src/SFA.DAS.Forecasting.Web/Views/Estimation/CostEstimation.cshtml
Labels: Ready to Release

#107 CI-841 -> Warning msg on account funds tab
  src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie6.css
  src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie7.css
  src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie8.css
  src/SFA.DAS.Forecasting.Web/Content/dist/css/screen.css
  src/SFA.DAS.Forecasting.Web/Content/src/sass/_custom.scss
  src/SFA.DAS.Forecasting.Web/Content/src/sass/_panels.scss
  src/SFA.DAS.Forecasting.Web/Views/Estimation/CostEstimation.cshtml
Labels: Ready for Test

#138 CI-941 -> Displaying next months projection first
  src/SFA.DAS.Forecasting.Web.AcceptanceTests/Features/Projection/DownloadForecastBalanceSheet.feature
  src/SFA.DAS.Forecasting.Web.AcceptanceTests/Features/Projection/DownloadForecastBalanceSheet.feature.cs
  src/SFA.DAS.Forecasting.Web.AcceptanceTests/Features/Projection/FundingProjectionPage_Accountprojection.feature
  src/SFA.DAS.Forecasting.Web.AcceptanceTests/Features/Projection/FundingProjectionPage_Accountprojection.feature.cs
  src/SFA.DAS.Forecasting.Web.AcceptanceTests/StepDefinition/DownloadForecastBalanceSheetSteps.cs
  src/SFA.DAS.Forecasting.Web.AcceptanceTests/StepDefinition/FundingProjectionPage_AccountprojectionSteps.cs
  src/SFA.DAS.Forecasting.Web.UnitTests/OrchestratorTests/ForecastingOrchestratorTests.cs
  src/SFA.DAS.Forecasting.Web/Orchestrators/ForcastingOrchestrator.cs
Labels: Ready for Test

#130 CI-856 CI-879 CI-916 CI-941
  src/SFA.DAS.Forecasting.Application/Balance/Services/BalanceDataService.cs
  src/SFA.DAS.Forecasting.Web.AcceptanceTests/Features/Projection/DownloadForecastBalanceSheet.feature
  src/SFA.DAS.Forecasting.Web.AcceptanceTests/Features/Projection/DownloadForecastBalanceSheet.feature.cs
  src/SFA.DAS.Forecasting.Web.AcceptanceTests/Features/Projection/FundingProjectionPage_Accountprojection.feature
  src/SFA.DAS.Forecasting.Web.AcceptanceTests/Features/Projection/FundingProjectionPage_Accountprojection.feature.cs
  src/SFA.DAS.Forecasting.Web.AcceptanceTests/StepDefinition/DownloadForecastBalanceSheetSteps.cs
  src/SFA.DAS.Forecasting.Web.AcceptanceTests/StepDefinition/FundingProjectionPage_AccountprojectionSteps.cs
  src/SFA.DAS.Forecasting.Web.UnitTests/OrchestratorTests/ForecastingOrchestratorTests.cs
  src/SFA.DAS.Forecasting.Web/Controllers/EstimationController.cs
  src/SFA.DAS.Forecasting.Web/Controllers/ForecastingController.cs
  src/SFA.DAS.Forecasting.Web/Global.asax.cs
  src/SFA.DAS.Forecasting.Web/Orchestrators/ForcastingOrchestrator.cs
  src/SFA.DAS.Forecasting.Web/ViewModels/BalanceViewModel.cs
  src/SFA.DAS.Forecasting.Web/Views/Estimation/StartEstimation.cshtml
  src/SFA.DAS.Forecasting.Web/Views/Forecasting/Balance.cshtml
Labels: Ready for Test

#104 CI-856 Updating content
  src/SFA.DAS.Forecasting.Web/Controllers/EstimationController.cs
  src/SFA.DAS.Forecasting.Web/Views/Estimation/StartEstimation.cshtml
Labels: Ready for Test

#105 CI-879 -> Styling disclaimer projection page
  src/SFA.DAS.Forecasting.Web/Views/Forecasting/Balance.cshtml
Labels: Ready for Test

#125 CI-904 tell app type page
  src/SFA.DAS.Forecasting.Domain/Estimations/AccountEstimationProjection.cs
  src/SFA.DAS.Forecasting.Models/Estimation/ApprenticeshipToAdd.cs
  src/SFA.DAS.Forecasting.Web/Controllers/EstimationController.cs
  src/SFA.DAS.Forecasting.Web/Orchestrators/Estimations/AddApprenticeshipOrchestrator.cs
  src/SFA.DAS.Forecasting.Web/SFA.DAS.Forecasting.Web.csproj
  src/SFA.DAS.Forecasting.Web/ViewModels/StartViweModel.cs
  src/SFA.DAS.Forecasting.Web/ViewModels/TypeOfApprenticeshipViewModel.cs
  src/SFA.DAS.Forecasting.Web/Views/Estimation/AddApprenticeships.cshtml
  src/SFA.DAS.Forecasting.Web/Views/Estimation/StartEstimation.cshtml
  src/SFA.DAS.Forecasting.Web/Views/Estimation/TypeOfApprenticeships.cshtml
Labels: do not merge

#141 Limit acceptance tests to use v1 of functions runtime
  src/SFA.DAS.Forecasting.AcceptanceTests/StepsBase.cs
Labels: Ready to Release
